### ISSUE TITLE
Create Issue Templates

### ISSUE THREAD

**Issue by TheENGR** [Cyberspace-Citizenship-Coefficient/.github#1]
- [x] Bugs
- [ ] Features

**Comment by TheENGR** [comment]
https://github.blog/2018-01-25-multiple-issue-and-pull-request-templates/
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by appasalvi** [comment]
I have put in a Issue/Bug Template and so I will be marking this card as completed.
